<?php
/**
 * @file
 * intercontinental_campaign.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function intercontinental_campaign_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-intercontinental-sidebar-me:node/1492
  $menu_links['menu-intercontinental-sidebar-me:node/1492'] = array(
    'menu_name' => 'menu-intercontinental-sidebar-me',
    'link_path' => 'node/1492',
    'router_path' => 'node/%',
    'link_title' => 'News',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: menu-intercontinental-sidebar-me:node/1494
  $menu_links['menu-intercontinental-sidebar-me:node/1494'] = array(
    'menu_name' => 'menu-intercontinental-sidebar-me',
    'link_path' => 'node/1494',
    'router_path' => 'node/%',
    'link_title' => 'Guide to Lhasa',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: menu-intercontinental-sidebar-me:node/1495
  $menu_links['menu-intercontinental-sidebar-me:node/1495'] = array(
    'menu_name' => 'menu-intercontinental-sidebar-me',
    'link_path' => 'node/1495',
    'router_path' => 'node/%',
    'link_title' => 'Local culture',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: menu-intercontinental-sidebar-me:node/1498
  $menu_links['menu-intercontinental-sidebar-me:node/1498'] = array(
    'menu_name' => 'menu-intercontinental-sidebar-me',
    'link_path' => 'node/1498',
    'router_path' => 'node/%',
    'link_title' => 'Jobs and training',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: menu-intercontinental-sidebar-me:node/1499
  $menu_links['menu-intercontinental-sidebar-me:node/1499'] = array(
    'menu_name' => 'menu-intercontinental-sidebar-me',
    'link_path' => 'node/1499',
    'router_path' => 'node/%',
    'link_title' => 'Partners',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: menu-intercontinental:<front>
  $menu_links['menu-intercontinental:<front>'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Free Tibet home',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '1',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-44',
  );
  // Exported menu link: menu-intercontinental:node/1490
  $menu_links['menu-intercontinental:node/1490'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => 'node/1490',
    'router_path' => 'node/%',
    'link_title' => 'Intercontinental',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
  );
  // Exported menu link: menu-intercontinental:node/1491
  $menu_links['menu-intercontinental:node/1491'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => 'node/1491',
    'router_path' => 'node/%',
    'link_title' => 'Basic',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '1',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: menu-intercontinental:node/1492
  $menu_links['menu-intercontinental:node/1492'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => 'node/1492',
    'router_path' => 'node/%',
    'link_title' => 'News',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-45',
  );
  // Exported menu link: menu-intercontinental:node/1493
  $menu_links['menu-intercontinental:node/1493'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => 'node/1493',
    'router_path' => 'node/%',
    'link_title' => 'About the hotel',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-49',
  );
  // Exported menu link: menu-intercontinental:node/1494
  $menu_links['menu-intercontinental:node/1494'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => 'node/1494',
    'router_path' => 'node/%',
    'link_title' => 'Guide to Lhasa',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-48',
  );
  // Exported menu link: menu-intercontinental:node/1496
  $menu_links['menu-intercontinental:node/1496'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => 'node/1496',
    'router_path' => 'node/%',
    'link_title' => 'Internet options',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-46',
  );
  // Exported menu link: menu-intercontinental:node/1497
  $menu_links['menu-intercontinental:node/1497'] = array(
    'menu_name' => 'menu-intercontinental',
    'link_path' => 'node/1497',
    'router_path' => 'node/%',
    'link_title' => 'Meetings & events',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-47',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('About the hotel');
  t('Basic');
  t('Free Tibet home');
  t('Guide to Lhasa');
  t('Intercontinental');
  t('Internet options');
  t('Jobs and training');
  t('Local culture');
  t('Meetings & events');
  t('News');
  t('Partners');


  return $menu_links;
}
