<?php

/**
 * @file
 * Miscellaneous overrides for Freetibet site
 */

function ftoverrides_form_search_block_form_alter(&$form,&$form_state,$form_id) {

	$form['background'] = array(
		'#type' => 'markup',
		'#markup' => '<div class="icon-search"></div>'
	);
	$form['search_block_form']['#attributes']['placeholder'] = t('Search words');
	$form['actions']['submit']['#value'] = t('Go');
}

/*
 * implements hook_node_view
*/
function ftoverrides_node_view($node,$view_mode) {
	switch ($node->type) {
		case 'media_section':
		case 'text':
		case 'box':
		case 'take_action':
		case 'key_points':
			if (node_is_page($node)) {
				$nid = ftoverrides_fetch_parent_nid($node);
				if ($nid > 0) {
					drupal_goto('node/' . $nid);
				}
			}
			$override_view_modes = array('full','default');
			if (in_array($view_mode,$override_view_modes)) {
				$mode = 'full';
				$items = field_get_items('node',$node,'field_layout_mode');
				if (!empty($items) && isset($items[0]) && isset($items[0]['value']) && is_string($items[0]['value'])) {
					$mode = $items[0]['value'];
				}
				if (!empty($items) && isset($items[0]) && isset($items[0]['value']) && is_string($items[0]['value'])) {
					$mode = $items[0]['value'];
				}
			
				$show_title = true;
				if (isset($node->field_show_title)) {
					$show_title = false;
					$items = field_get_items('node',$node,'field_show_title');
					if (!empty($items) && isset($items[0]) && isset($items[0]['value']) && is_numeric($items[0]['value'])) {
						$show_title = (bool) $items[0]['value'];
					}
					if ($mode != 'full' && empty($node->page_viewmode)) {
						$node->page_viewmode = $mode;
						$node->content = node_view($node,$mode);
					}
					if (!$show_title && isset($node->content['title'])) {
						unset($node->content['title']);
					}
				}
			}
			break;
		case 'donation':
			if (isset($node->content['add_to_cart']) && isset($node->content['add_to_cart']['#form'])) {
				$add_to_cart_form =& $node->content['add_to_cart']['#form'];
				if (isset($add_to_cart_form['donate_amount']) && isset($add_to_cart_form['varprice'])) {
					$add_to_cart_form['donate_amount'] = array(
						'#type' => 'hidden',
						'#name' => 'donate_amount',
						'#value' => $add_to_cart_form['varprice']['#default_value']
					);
				}
			}
			break;
		case 'page':
			ftoverrides_set_first_page_section_position($node,$view_mode);
			break;
	}
}

function ftoverrides_set_first_page_section_position($node,$view_mode) {
	if ($view_mode == 'full' && isset($node->field_page_sections) && isset($node->content['field_page_sections']) && isset($node->content['top'])) {
		$move_first_page_section = _ftoverrides_set_first_page_section_position($node,$view_mode);
	}
	if (!$move_first_page_section  && isset($node->content['top'])) {
		unset($node->content['top']);
	}
}

function _ftoverrides_set_first_page_section_position($node,$view_mode) {
	$move_first_page_section = false;
	if (isset($node->content['field_page_sections']['#items']) && is_array($node->content['field_page_sections']['#items'])) {
		$num_items = count($node->content['field_page_sections']['#items']);
		if ($num_items > 0 ) {
			
			$field_items = field_get_items('node',$node,'field_section_position');
			if (!empty($field_items) && isset($field_items[0]['value'])) {
				$value = (int) $field_items[0]['value'];
				if ($value > 0) {
					$move_first_page_section = true;
					$setSliderWeight = false;
					switch ($value) {
						case 2:
							$setSliderWeight = isset($node->content['field_slide']);
							break;
					}
				}
			}
			if ($move_first_page_section) {
				$items = $node->content['field_page_sections']['#items'];
				$firstItem = array_shift($items);
				$last_index = $num_items - 1;

				for ($i=0;$i < $num_items;$i++) {
					if ($i == 0) {
						$firstRenderItem = $node->content['field_page_sections'][$i];
					}
					if ($i < $last_index) {
						$node->content['field_page_sections'][$i] = $node->content['field_page_sections'][($i+1)];
					}
					else {
						unset($node->content['field_page_sections'][$i]);
					}
				}
				$node->content['field_page_sections']['#items'] = $items;
			}
			$node->content['top']['#items'] = array($firstItem);
			$node->content['top'][0] = array(
				'#markup' => render($firstRenderItem)
			);
			if ($setSliderWeight) {
				$node->content['top']['#weight'] = -1000;
				$node->content['field_slide']['#weight'] = -999;
			}
		}
	}
	return $move_first_page_section;
}

/*
 * Implements hook_ds_fields_info
*/

function ftoverrides_ds_fields_info($entity_type) {
	$fields = array();

	switch ($entity_type) {
		case 'file':
			$fields['related_text'] = array(
					'title' => t('Text in referencing entity'),
					'field_type' => DS_FIELD_TYPE_FUNCTION,
					'function' => 'ftoverrides_related_text',
					'properties' => array(
							'settings' => array(
							),
					)
			);
			return array($entity_type => $fields);
			break;
		case 'node':
			$fields['top'] = array(
					'title' => t('Target top section'),
					'field_type' => DS_FIELD_TYPE_FUNCTION,
					'function' => 'ftoverrides_top_section',
					'properties' => array(
							'settings' => array(
							),
					)
			);
			return array($entity_type => $fields);
			break;
	}
	return;
}

function ftoverrides_top_section($field) {
	if (isset($field['entity']) && is_object($field['entity']) && $field['entity_type'] == 'node') {
		return t("Top section");
	}
}


function ftoverrides_fetch_parent_nid($node) {
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
	->fieldCondition('field_page_sections', 'target_id', $node->nid, '=');
	$result = $query->execute();
	if (is_array($result) && isset($result['node']) && is_array($result['node']) && !empty($result['node'])) {
		$nids = array_keys($result['node']);
		return array_shift($nids);
	}
	return 0;
}

function ftoverrides_related_text($field) {
	if (isset($field['entity']) && is_object($field['entity']) && $field['entity_type'] == 'file') {
		$text = '';
		$entity = $field['entity'];
		if ($entity->referencing_entity instanceof FieldCollectionItemEntity) {
			if (isset($entity->referencing_entity->field_text)) {
				$items = field_get_items('field_collection_item',$entity->referencing_entity,'field_text');
				if (is_array($items) && !empty($items) && isset($items[0]['safe_value'])) {
					if (is_string($items[0]['safe_value'])) {
						return $items[0]['safe_value'];
					}
				}
			}
			return $text;
		}
	}
}


function ftoverrides_form_node_form_alter(&$form, $form_state, $form_id) {
	module_load_include('inc','ftoverrides','ftoverrides.edit');
	_ftoverrides_form_node_form_alter($form,$form_state,$form_id);
}

function ftoverrides_get_available_view_modes($bundle = NULL) {
	$view_modes = array();
	$prefix = 'field_bundle_settings_node__';
	$data = variable_get($prefix . $bundle, NULL);
	$excludeViewModes = array('search_index','summary','teaser','default','full');
	$view_modes = array(
			'full' => 'Full (Default full page view)',
	);
	if (is_array($data) && isset($data['view_modes']) && is_array($data['view_modes']) && !empty($data['view_modes'])) {
		foreach ($data['view_modes'] as $name => $data) {
			if ($data['custom_settings'] && !in_array($name,$excludeViewModes)) {
				$view_modes[$name] = $name;
			}
		}
	}
	return $view_modes;
}


function ftoverrides_wysiwyg_editor_settings_alter(&$settings, $context) {
	if ($context['profile']->editor == 'ckeditor') {
		switch ($context['profile']->format) {
			case 'full_html':
				$settings['height'] = 360;
				break;
			case 'filtered_html':
				$settings['height'] = 200;
				break;
		}
	}
}